name: ${project.name}
version: ${project.version}
main: xyz.upperlevel.slimyguis.SlimyGuis
author: upperlevel
description: ${project.description}
depend: [Uppercore]

commands:
  slimyguis:
    description: Commands for SlimyGuis