name: ${project.name}
version: ${project.version}
main: xyz.upperlevel.slimyguis.SlimyGuis
author: upperlevel
description: ${project.description}

depend: [Uppercore]
softdepend: [PlaceholderAPI, Vault]

commands:
  slimyguis:
    description: Commands for SlimyGuis.

permissions:
  slimyguis.*:
    description: Gives access to all SlimyGuis features
    children:
      slimyguis.command.*: true

  slimyguis.command.*:
    description: Gives access to all SlimyGuis commands
    children:
      slimyguis.command.open: true
      slimyguis.command.list: true
      slimyguis.command.scripts: true

  slimyguis.command.open:
    description: Allows you to openGui the guis by commands
    default: true

  slimyguis.command.list:
    description: Allows you to list all the registered guis
    default: op

  slimyguis.command.scripts:
    description: Allows you to list all the loaded scripts
    default: op
